version: "3"
services:
  scrimpweb:
    image: "slaatipton/scrimp:rc-1"
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
    depends_on:
      - scrimpsql
  scrimpsql:
    image: "microsoft/mssql-server-linux"
    ports:
      - "1438:1433"
    networks:
      - webnet
    volumes:
      - scrimpdata:/var/opt/mssql
    environment:
      SA_PASSWORD: "3sU12BE1"
      ACCEPT_EULA: "Y"

volumes:
  scrimpdata:

networks:
  webnet:
    external:
      name: webnet